remote_theme: just-the-docs/just-the-docs

title: Validator Resources
description: A community resource for LUKSO network validators
# baseurl: "/docs-website" # the subpath of your site, e.g. /blog
# url: "https://keez-robg.github.io/ # the base hostname & protocol for your site, e.g. http://example.com

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/KEEZ-RobG/docs-website" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Enable or disable heading anchors
heading_anchors: true

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil
